# SETTINGS FILE
## General settings 
input:
  folder: data
  fname: clean_transactions.csv
output_folder: output
models: dense
aggregation: day # one of [None, 'hour','day','month'] 
train_date: '2018-08-01'
steps_back: 14
forecast_window: 7 
batch_size: 32
online: False
multioutput: True
replace: False
batch_size: 32
stations: #If any given, multioutput model is turned off. 